version: '3.8'

services:
    laravel:
        build:
            context: .
        volumes:
            - .:/var/www
        expose:
            - 9000

    nginx:
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - laravel

    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: laravel
            MYSQL_USER: sail
            MYSQL_PASSWORD: password
        volumes:
            - 'sail-mysql:/var/lib/mysql'

volumes:
    sail-mysql:
